### PR TITLE
Solve error in editorJS v2.29.0 

### LINKED ISSUE #122: Doesn't work with editorjs 2.29.0
Hello! Thanks for your work!

Editorjs v2.29.0 catches the exception
```
TypeError: Argument 1 ('target') to MutationObserver.observe must be an instance of Node
```
and rejects the tool installation/usage.

Снимок экрана 2024-03-18 в 16 39 31

### PR DESCRIPTION
**Pull request by MarioRodriguezS**
## Description

Fix #122

The issue was related to the editorjs version, in version 2.29.0 the elements with classes `ct` and `ct__content` are rendered after the plugin constructor; in the plugin, these elements are used to customize the tooltip, so the plugin was not set correctly. The solution is to customize the tooltip after the plugin constructor is called, specifically, it is possible to use the plugin `render` method.

The solution was tested in other EditorJS versions without any issues.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -275,7 +275,7 @@ export default class Tooltip {
     this.tooltipInput.placeholder = this.placeholder;
     this.tooltipInput.classList.add(this.api.styles.input);
     this.tooltipInput.classList.add(this.CSS.input);
-    if (this.spanTooltip) {
+    if (this.spanTooltip && this.spanTooltip.dataset.tooltip) {
```
Comment (miguelnietoa) [inline src/index.js:278]: @MarioRodriguezS  Please review if we could refactor this way
```suggestion
    if (this.spanTooltip?.dataset?.tooltip) {
```

**Review by miguelnietoa — APPROVED** [review]
Thanks @MarioRodriguezS 🚀
